import time
print('                            +                +')
time.sleep(0.5)
print('                        +             +           +')
time.sleep(0.5)
print('                             +                  +')
time.sleep(0.5)
print('                                  +        +')
time.sleep(0.5)
print('                                       +')
time.sleep(0.5)
print('                                       +')
print('                                       +')
print('                                       +')
print('                                       +')
